#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
export NDK_ROOT=/home/huang/android-ndk-r25c
export PATH=$PATH:$NDK_ROOT
export BUILD_THREADS=$(nproc --all)
export BUILD_GUEST='x86_64-softmmu,i386-softmmu,aarch64-softmmu,arm-softmmu,ia64-softmmu'
export USE_GTK=true

make clean

export BUILD_HOST='arm64-v8a'
make limbo

export BUILD_HOST='armeabi-v7a'
make limbo

export BUILD_HOST='x86'
make limbo

export BUILD_HOST='x86_64'
make limbo
