#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
export NDK_ROOT=/home/huang/android-ndk-r25c
export PATH=$PATH:$NDK_ROOT
export BUILD_THREADS=$(nproc --all)
export BUILD_GUEST='ia64-softmmu'
export BUILD_HOST='armeabi-v7a'
export USE_GTK=true

make limbo
