#!/bin/bash
export NDK_ROOT=/home/huang/android-ndk-r28c
export PATH=$PATH:$NDK_ROOT
export BUILD_THREADS=$(nproc --all)
export BUILD_GUEST='ia64-softmmu'
export BUILD_HOST='arm64-v8a'
export USE_GTK=true
# 完整构建链: ffi -> glib -> pixman -> gtk(gtk4android) -> qemu -> limbo
make limbo
