name: build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      build_guest:
        description: '模拟架构'
        required: true
        default: 'x86_64-softmmu,aarch64-softmmu,ia64-softmmu'
        type: string

jobs:
  build_linux:
    name: Linux Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 检出代码
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1
        with:
          packages: 'ndk;25.2.9519653'

      - name: 安装依赖
        run: |
          sudo apt-get install make autoconf automake git binutils python3 \
            libtool-bin pkg-config flex bison gettext texinfo rsync \
            gtk-doc-tools python3-pip ninja-build meson

      - name: 克隆代码
        run: |
          #Make sure you're under the jni directory
          cd ./limbo-android-lib/src/main/jni
          
          # Now download the source code for the external libraries and unzip them under the jni directory
          #Note: if some of these file links don't download with wget use your browser to download them
          
          ##### GET glib
          wget --quiet https://download.gnome.org/sources/glib/2.66/glib-2.66.8.tar.xz -P /tmp/
          tar -xJf /tmp/glib-2.66.8.tar.xz
          mv glib-2.66.8 glib
          
          cd glib
          patch -p1 < ../patches/glib-2.66.8.patch
          cd ..
          
          ##### GET libffi
          wget --quiet https://sourceware.org/pub/libffi/libffi-3.3.tar.gz -P /tmp/
          tar -xzf /tmp/libffi-3.3.tar.gz
          mv libffi-3.3 libffi
          
          ##### GET pixman
          wget --quiet https://www.cairographics.org/releases/pixman-0.40.0.tar.gz -P /tmp/
          tar -xzf /tmp/pixman-0.40.0.tar.gz
          mv pixman-0.40.0 pixman
          
          ##### GET SDL2
          wget --quiet https://www.libsdl.org/release/SDL2-2.0.8.tar.gz -P /tmp/
          tar -xzf /tmp/SDL2-2.0.8.tar.gz
          mv SDL2-2.0.8 SDL2
          
          cd SDL2
          patch -p1 < ../patches/sdl2-2.0.8.patch

      - name: Build QEMU
        run: |
          cd limbo-android-lib/src/main/jni
          export NDK_ROOT=${ANDROID_SDK_ROOT}/ndk/25.2.9519653
          export PATH=$PATH:$NDK_ROOT
          export BUILD_THREADS=$(nproc)
          export BUILD_GUEST=${{ github.event.inputs.build_guest || 'x86_64-softmmu,aarch64-softmmu,ia64-softmmu' }}
          make limbo

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew assemble
      - name: 上传apk构建产物
        uses: actions/upload-artifact@v7.0.1
        with:
          name: build_apk_output.zip
          path: |
            limbo-android-ia64/build/outputs/apk/**/*.apk
            limbo-android-arm/build/outputs/apk/**/*.apk
            limbo-android-x86/build/outputs/apk/**/*.apk